### ISSUE TITLE
Model do not have subsystem?

### ISSUE THREAD

**Issue by juz4karen** [MD-Anderson-Bioinformatics/SAMMI#5]
Hi,

I tried the tutorial example that I downloaded both Recon3D.json and .xml file, then tried to upload the model file in parse in SAMMI, then I realised there's no 'subsystem' option for the .xml file but for .json file yes, is there any reason why?

I found it confusing cause I wanted to load my model and visualise it in subsystem too, but it don't have the option too. I wonder is it because of my genome assembly file or the model built....

Fyi, I downloaded Klebsiella pneumoniae isolate BAA-2146 genome file from NCBI database and built the model using CarveMe.

Hope to advise.

Regards,
Karen

**Comment by schultzdre** [comment]
Hi Karen,
Xml files are a little trickier to parse, but if the subsystem information is in there they should show up as an option. Do you see subsystem information in your xml export?
Andre

**Comment by juz4karen** [comment]
Hi Andre,

Thanks for attending my issue.

Nope, actually I don't see subsystem information in my model xml file. I guess the information is lacking in the library database of the software during my model building. 

Regards,
Karen

**Comment by schultzdre** [comment]
Hi Karen,
No problem! Thank for using SAMMI.
Best,
Andre
